### ISSUE TITLE
Unable to share Youtube video if helper script.yatse.kodi enabled

### ISSUE THREAD

**Issue by mdef** [Tolriq/repository.yatse.kodi#22]
Error from kodi logs:
```
2020-08-28 14:22:37.315 T:3376     INFO <general>: initializing python engine.
2020-08-28 14:22:51.402 T:3376    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'xbmcgui.ListItem' object has no attribute 'setThumbnailImage'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.yatse.kodi/default.py", line 29, in <module>
                                                       commands[argument['action']](argument)
                                                     File "/storage/.kodi/addons/script.yatse.kodi/lib/share.py", line 27, in run
                                                       handle_unresolved_url(argument['data'], action)
                                                     File "/storage/.kodi/addons/script.yatse.kodi/lib/share.py", line 103, in handle_unresolved_url
                                                       result = resolve_with_youtube_dl(url, {'format': 'best', 'no_color': 'true', 'ignoreerrors': 'true'}, action)
                                                     File "/storage/.kodi/addons/script.yatse.kodi/lib/share.py", line 68, in resolve_with_youtube_dl
                                                       utils.play_url(result['url'], action, result)
                                                     File "/storage/.kodi/addons/script.yatse.kodi/lib/utils.py", line 85, in play_url
                                                       list_item = get_kodi_list_item(meta_data)
                                                     File "/storage/.kodi/addons/script.yatse.kodi/lib/utils.py", line 167, in get_kodi_list_item
                                                       list_item.setThumbnailImage(meta_data['thumbnail'])
                                                   AttributeError: 'xbmcgui.ListItem' object has no attribute 'setThumbnailImage'
                                                   -->End of Python script error report<--
```
LibreELEC version:
```
LibreELEC (community): devel-20200815101041-6063236 (H3.arm)

```
Please let me know if any additional information is required.
Thank You for the project.

**Comment by Tolriq** [comment]
Update to 2.2.0 ;)

**Comment by mdef** [comment]
install of 2.2.0.is failing with the following
tail -n 50 .kodi/temp/kodi.log
```
CAddonInstallJob[script.yatse.kodi]: The dependency on xbmc.python version 2.1.0 could not be satisfied.
Any other suggestions?
```

**Comment by Tolriq** [comment]
Well for matrix it's the 92.2.0 but just update the addon if you installed the correct version it will update to the proper one.
